# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=1024)),
                ('sha1_hash', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1024)),
                ('notes', models.TextField(null=True)),
                ('posted_date', models.DateTimeField()),
                ('size', models.DecimalField(decimal_places=3, max_digits=12)),
                ('product_key_required', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='productfamily',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msdn.ProductGroup'),
        ),
        migrations.AddField(
            model_name='file',
            name='product_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msdn.ProductFamily'),
        ),
    ]
