# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msdn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='msdn.Language'),
        ),
    ]
